import React from "react";

// Dotted icon (one input fanning out to three outputs), generated by a dot-trace script: outlines drawn as
// evenly spaced dots in currentColor, 33 dots in a 64x64 box.
export default function DottedEutxo(props) {
  return (
    <svg viewBox="0 0 64 64" fill="currentColor" aria-hidden="true" {...props}>
      <circle cx="19" cy="32" r="2.3" />
      <circle cx="16.66" cy="37.66" r="2.3" />
      <circle cx="11" cy="40" r="2.3" />
      <circle cx="5.34" cy="37.66" r="2.3" />
      <circle cx="3" cy="32" r="2.3" />
      <circle cx="5.34" cy="26.34" r="2.3" />
      <circle cx="11" cy="24" r="2.3" />
      <circle cx="16.66" cy="26.34" r="2.3" />
      <circle cx="59" cy="9" r="2.3" />
      <circle cx="55.55" cy="13.76" r="2.3" />
      <circle cx="49.95" cy="11.94" r="2.3" />
      <circle cx="49.95" cy="6.06" r="2.3" />
      <circle cx="55.55" cy="4.24" r="2.3" />
      <circle cx="59" cy="32" r="2.3" />
      <circle cx="55.55" cy="36.76" r="2.3" />
      <circle cx="49.95" cy="34.94" r="2.3" />
      <circle cx="49.95" cy="29.06" r="2.3" />
      <circle cx="55.55" cy="27.24" r="2.3" />
      <circle cx="59" cy="55" r="2.3" />
      <circle cx="55.55" cy="59.76" r="2.3" />
      <circle cx="49.95" cy="57.94" r="2.3" />
      <circle cx="49.95" cy="52.06" r="2.3" />
      <circle cx="55.55" cy="50.24" r="2.3" />
      <circle cx="27" cy="32" r="2.3" />
      <circle cx="31.5" cy="28.17" r="2.3" />
      <circle cx="36" cy="24.33" r="2.3" />
      <circle cx="40.5" cy="20.5" r="2.3" />
      <circle cx="45" cy="16.67" r="2.3" />
      <circle cx="40.5" cy="32" r="2.3" />
      <circle cx="31.5" cy="35.83" r="2.3" />
      <circle cx="36" cy="39.67" r="2.3" />
      <circle cx="40.5" cy="43.5" r="2.3" />
      <circle cx="45" cy="47.33" r="2.3" />
    </svg>
  );
}
