import React from "react";

// Dotted icon (calculator with a display row and button grid), generated by a dot-trace script: outlines drawn as
// evenly spaced dots in currentColor, 33 dots in a 64x64 box.
export default function DottedCalculator(props) {
  return (
    <svg viewBox="0 0 64 64" fill="currentColor" aria-hidden="true" {...props}>
      <circle cx="20" cy="10" r="2.3" />
      <circle cx="26" cy="10" r="2.3" />
      <circle cx="32" cy="10" r="2.3" />
      <circle cx="38" cy="10" r="2.3" />
      <circle cx="44" cy="10" r="2.3" />
      <circle cx="48" cy="14" r="2.3" />
      <circle cx="48" cy="20.33" r="2.3" />
      <circle cx="48" cy="26.67" r="2.3" />
      <circle cx="48" cy="33" r="2.3" />
      <circle cx="48" cy="39.33" r="2.3" />
      <circle cx="48" cy="45.67" r="2.3" />
      <circle cx="48" cy="52" r="2.3" />
      <circle cx="44" cy="56" r="2.3" />
      <circle cx="38" cy="56" r="2.3" />
      <circle cx="32" cy="56" r="2.3" />
      <circle cx="26" cy="56" r="2.3" />
      <circle cx="20" cy="56" r="2.3" />
      <circle cx="16" cy="52" r="2.3" />
      <circle cx="16" cy="45.67" r="2.3" />
      <circle cx="16" cy="39.33" r="2.3" />
      <circle cx="16" cy="33" r="2.3" />
      <circle cx="16" cy="26.67" r="2.3" />
      <circle cx="16" cy="20.33" r="2.3" />
      <circle cx="16" cy="14" r="2.3" />
      <circle cx="25" cy="20" r="2.3" />
      <circle cx="32" cy="20" r="2.3" />
      <circle cx="39" cy="20" r="2.3" />
      <circle cx="25" cy="34" r="2.3" />
      <circle cx="32" cy="34" r="2.3" />
      <circle cx="39" cy="34" r="2.3" />
      <circle cx="25" cy="45" r="2.3" />
      <circle cx="32" cy="45" r="2.3" />
      <circle cx="39" cy="45" r="2.3" />
    </svg>
  );
}
