import React from "react";

// Dotted icon (ballot with a check mark), generated by a dot-trace script: outlines drawn as
// evenly spaced dots in currentColor, 26 dots in a 64x64 box.
export default function DottedBallot(props) {
  return (
    <svg viewBox="0 0 64 64" fill="currentColor" aria-hidden="true" {...props}>
      <circle cx="18" cy="12" r="2.3" />
      <circle cx="25" cy="12" r="2.3" />
      <circle cx="32" cy="12" r="2.3" />
      <circle cx="39" cy="12" r="2.3" />
      <circle cx="46" cy="12" r="2.3" />
      <circle cx="52" cy="18" r="2.3" />
      <circle cx="52" cy="25" r="2.3" />
      <circle cx="52" cy="32" r="2.3" />
      <circle cx="52" cy="39" r="2.3" />
      <circle cx="52" cy="46" r="2.3" />
      <circle cx="46" cy="52" r="2.3" />
      <circle cx="39" cy="52" r="2.3" />
      <circle cx="32" cy="52" r="2.3" />
      <circle cx="25" cy="52" r="2.3" />
      <circle cx="18" cy="52" r="2.3" />
      <circle cx="12" cy="46" r="2.3" />
      <circle cx="12" cy="39" r="2.3" />
      <circle cx="12" cy="32" r="2.3" />
      <circle cx="12" cy="25" r="2.3" />
      <circle cx="12" cy="18" r="2.3" />
      <circle cx="21" cy="32" r="2.3" />
      <circle cx="24.5" cy="35.5" r="2.3" />
      <circle cx="28" cy="39" r="2.3" />
      <circle cx="33" cy="34" r="2.3" />
      <circle cx="38" cy="29" r="2.3" />
      <circle cx="43" cy="24" r="2.3" />
    </svg>
  );
}
