import React from "react";

// Dotted icon (balance scale), generated by a dot-trace script: outlines drawn as
// evenly spaced dots in currentColor, 32 dots in a 64x64 box.
export default function DottedScale(props) {
  return (
    <svg viewBox="0 0 64 64" fill="currentColor" aria-hidden="true" {...props}>
      <circle cx="32" cy="10" r="2.3" />
      <circle cx="32" cy="16.29" r="2.3" />
      <circle cx="32" cy="22.57" r="2.3" />
      <circle cx="32" cy="28.86" r="2.3" />
      <circle cx="32" cy="35.14" r="2.3" />
      <circle cx="32" cy="41.43" r="2.3" />
      <circle cx="32" cy="47.71" r="2.3" />
      <circle cx="32" cy="54" r="2.3" />
      <circle cx="22" cy="54" r="2.3" />
      <circle cx="42" cy="54" r="2.3" />
      <circle cx="12" cy="16" r="2.3" />
      <circle cx="18.67" cy="16" r="2.3" />
      <circle cx="25.33" cy="16" r="2.3" />
      <circle cx="38.67" cy="16" r="2.3" />
      <circle cx="45.33" cy="16" r="2.3" />
      <circle cx="52" cy="16" r="2.3" />
      <circle cx="3" cy="36" r="2.3" />
      <circle cx="6" cy="29.33" r="2.3" />
      <circle cx="9" cy="22.67" r="2.3" />
      <circle cx="15" cy="22.67" r="2.3" />
      <circle cx="18" cy="29.33" r="2.3" />
      <circle cx="21" cy="36" r="2.3" />
      <circle cx="15" cy="36" r="2.3" />
      <circle cx="9" cy="36" r="2.3" />
      <circle cx="43" cy="36" r="2.3" />
      <circle cx="46" cy="29.33" r="2.3" />
      <circle cx="49" cy="22.67" r="2.3" />
      <circle cx="55" cy="22.67" r="2.3" />
      <circle cx="58" cy="29.33" r="2.3" />
      <circle cx="61" cy="36" r="2.3" />
      <circle cx="55" cy="36" r="2.3" />
      <circle cx="49" cy="36" r="2.3" />
    </svg>
  );
}
