import React from "react";

// Dotted icon (two overlapping coins), generated by a dot-trace script: outlines drawn as
// evenly spaced dots in currentColor, 27 dots in a 64x64 box.
export default function DottedCoins(props) {
  return (
    <svg viewBox="0 0 64 64" fill="currentColor" aria-hidden="true" {...props}>
      <circle cx="41" cy="38" r="2.3" />
      <circle cx="39.78" cy="44.12" r="2.3" />
      <circle cx="36.31" cy="49.31" r="2.3" />
      <circle cx="31.12" cy="52.78" r="2.3" />
      <circle cx="25" cy="54" r="2.3" />
      <circle cx="18.88" cy="52.78" r="2.3" />
      <circle cx="13.69" cy="49.31" r="2.3" />
      <circle cx="10.22" cy="44.12" r="2.3" />
      <circle cx="9" cy="38" r="2.3" />
      <circle cx="10.22" cy="31.88" r="2.3" />
      <circle cx="13.69" cy="26.69" r="2.3" />
      <circle cx="18.88" cy="23.22" r="2.3" />
      <circle cx="25" cy="22" r="2.3" />
      <circle cx="31.12" cy="23.22" r="2.3" />
      <circle cx="36.31" cy="26.69" r="2.3" />
      <circle cx="39.78" cy="31.88" r="2.3" />
      <circle cx="57" cy="25" r="2.3" />
      <circle cx="55.78" cy="31.12" r="2.3" />
      <circle cx="52.31" cy="36.31" r="2.3" />
      <circle cx="47.12" cy="39.78" r="2.3" />
      <circle cx="29.69" cy="13.69" r="2.3" />
      <circle cx="34.88" cy="10.22" r="2.3" />
      <circle cx="41" cy="9" r="2.3" />
      <circle cx="47.12" cy="10.22" r="2.3" />
      <circle cx="52.31" cy="13.69" r="2.3" />
      <circle cx="55.78" cy="18.88" r="2.3" />
      <circle cx="25" cy="38" r="2.3" />
    </svg>
  );
}
