import React from "react";

// Dotted icon (Erlenmeyer flask with a liquid line), generated by a dot-trace script: outlines drawn as
// evenly spaced dots in currentColor, 26 dots in a 64x64 box.
export default function DottedFlask(props) {
  return (
    <svg viewBox="0 0 64 64" fill="currentColor" aria-hidden="true" {...props}>
      <circle cx="26" cy="10" r="2.3" />
      <circle cx="26" cy="15.33" r="2.3" />
      <circle cx="26" cy="20.67" r="2.3" />
      <circle cx="26" cy="26" r="2.3" />
      <circle cx="23.4" cy="31.6" r="2.3" />
      <circle cx="20.8" cy="37.2" r="2.3" />
      <circle cx="18.2" cy="42.8" r="2.3" />
      <circle cx="15.6" cy="48.4" r="2.3" />
      <circle cx="13" cy="54" r="2.3" />
      <circle cx="19.33" cy="54" r="2.3" />
      <circle cx="25.67" cy="54" r="2.3" />
      <circle cx="32" cy="54" r="2.3" />
      <circle cx="38.33" cy="54" r="2.3" />
      <circle cx="44.67" cy="54" r="2.3" />
      <circle cx="51" cy="54" r="2.3" />
      <circle cx="48.4" cy="48.4" r="2.3" />
      <circle cx="45.8" cy="42.8" r="2.3" />
      <circle cx="43.2" cy="37.2" r="2.3" />
      <circle cx="40.6" cy="31.6" r="2.3" />
      <circle cx="38" cy="26" r="2.3" />
      <circle cx="38" cy="20.67" r="2.3" />
      <circle cx="38" cy="15.33" r="2.3" />
      <circle cx="38" cy="10" r="2.3" />
      <circle cx="27" cy="44" r="2.3" />
      <circle cx="32" cy="44" r="2.3" />
      <circle cx="37" cy="44" r="2.3" />
    </svg>
  );
}
