import React from "react";

// Dotted icon (three linked nodes), generated by a dot-trace script: outlines drawn as
// evenly spaced dots in currentColor, 31 dots in a 64x64 box.
export default function DottedNetwork(props) {
  return (
    <svg viewBox="0 0 64 64" fill="currentColor" aria-hidden="true" {...props}>
      <circle cx="40" cy="15" r="2.3" />
      <circle cx="37.66" cy="20.66" r="2.3" />
      <circle cx="32" cy="23" r="2.3" />
      <circle cx="26.34" cy="20.66" r="2.3" />
      <circle cx="24" cy="15" r="2.3" />
      <circle cx="26.34" cy="9.34" r="2.3" />
      <circle cx="32" cy="7" r="2.3" />
      <circle cx="37.66" cy="9.34" r="2.3" />
      <circle cx="22" cy="48" r="2.3" />
      <circle cx="19.66" cy="53.66" r="2.3" />
      <circle cx="14" cy="56" r="2.3" />
      <circle cx="8.34" cy="53.66" r="2.3" />
      <circle cx="6" cy="48" r="2.3" />
      <circle cx="8.34" cy="42.34" r="2.3" />
      <circle cx="14" cy="40" r="2.3" />
      <circle cx="19.66" cy="42.34" r="2.3" />
      <circle cx="58" cy="48" r="2.3" />
      <circle cx="55.66" cy="53.66" r="2.3" />
      <circle cx="50" cy="56" r="2.3" />
      <circle cx="44.34" cy="53.66" r="2.3" />
      <circle cx="42" cy="48" r="2.3" />
      <circle cx="44.34" cy="42.34" r="2.3" />
      <circle cx="50" cy="40" r="2.3" />
      <circle cx="55.66" cy="42.34" r="2.3" />
      <circle cx="26" cy="26" r="2.3" />
      <circle cx="23" cy="31.5" r="2.3" />
      <circle cx="20" cy="37" r="2.3" />
      <circle cx="32" cy="48" r="2.3" />
      <circle cx="44" cy="37" r="2.3" />
      <circle cx="41" cy="31.5" r="2.3" />
      <circle cx="38" cy="26" r="2.3" />
    </svg>
  );
}
