import React from "react";

// Dotted icon (open padlock, staking without a lock-up), generated by a dot-trace script: outlines drawn as
// evenly spaced dots in currentColor, 25 dots in a 64x64 box.
export default function DottedLockOpen(props) {
  return (
    <svg viewBox="0 0 64 64" fill="currentColor" aria-hidden="true" {...props}>
      <circle cx="19" cy="31" r="2.3" />
      <circle cx="25.5" cy="31" r="2.3" />
      <circle cx="32" cy="31" r="2.3" />
      <circle cx="38.5" cy="31" r="2.3" />
      <circle cx="45" cy="31" r="2.3" />
      <circle cx="51" cy="37" r="2.3" />
      <circle cx="51" cy="43.5" r="2.3" />
      <circle cx="51" cy="50" r="2.3" />
      <circle cx="45" cy="56" r="2.3" />
      <circle cx="38.5" cy="56" r="2.3" />
      <circle cx="32" cy="56" r="2.3" />
      <circle cx="25.5" cy="56" r="2.3" />
      <circle cx="19" cy="56" r="2.3" />
      <circle cx="13" cy="50" r="2.3" />
      <circle cx="13" cy="43.5" r="2.3" />
      <circle cx="13" cy="37" r="2.3" />
      <circle cx="21" cy="24" r="2.3" />
      <circle cx="21" cy="17" r="2.3" />
      <circle cx="23.1" cy="10.53" r="2.3" />
      <circle cx="28.6" cy="6.54" r="2.3" />
      <circle cx="35.4" cy="6.54" r="2.3" />
      <circle cx="40.9" cy="10.53" r="2.3" />
      <circle cx="43" cy="17" r="2.3" />
      <circle cx="32" cy="40" r="2.3" />
      <circle cx="32" cy="47" r="2.3" />
    </svg>
  );
}
