/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  // Define sidebars here for subfolders of docs/
  getInvolvedSidebar: [{type: 'autogenerated', dirName: 'get-involved'}],

  // Put sinlge markdown files without a sidebar in docs/ and use displayed_sidebar: null
 
};

export default sidebars;
