//
// Custom Docusaurus plugin: registers a static route at /apps/<slug> for every entry
// in src/data/apps-metadata.json (generated by scripts/generate-apps-metadata.js).
// Each route renders src/components/AppDetail with the app's metadata injected as a module.
//

const path = require('path');

module.exports = function appsRoutesPlugin(context) {
  return {
    name: 'apps-routes',

    async loadContent() {
      const dataPath = path.join(
        context.siteDir,
        'src/data/apps-metadata.json'
      );
      return require(dataPath);
    },

    async contentLoaded({ content, actions }) {
      const { addRoute, createData } = actions;
      // baseUrl is locale-aware: "/" for default locale, "/de/" / "/ja/" / etc.
      // Concatenating it onto each route path makes the plugin work for every locale build.
      const baseUrl = context.baseUrl;
      for (const app of content) {
        const dataFile = await createData(
          `apps-detail-${app.slug}.json`,
          JSON.stringify(app)
        );
        addRoute({
          path: `${baseUrl}apps/${app.slug}`,
          component: '@site/src/components/AppDetail',
          modules: { app: dataFile },
          exact: true,
        });
      }
    },
  };
};
